export const keymap = [
  '',
  'Escape:func:50::func:Esc',
  'Backquote:key:::symbol:`~`~ёЁЁё',
  'Digit1:key:::symbol:1!1!1!1!',
  'Digit2:key:::symbol:2@2@2"2"',
  'Digit3:key:::symbol:3#3#3№3№',
  'Digit4:key:::symbol:4$4$4;4;',
  'Digit5:key:::symbol:5%5%5%5%',
  'Digit6:key:::symbol:6^6^6:6:',
  'Digit7:key:::symbol:7&7&7?7?',
  'Digit8:key:::symbol:8*8*8*8*',
  'Digit9:key:::symbol:9(9(9(9(',
  'Digit0:key:::symbol:0)0)0)0)',
  'Minus:key:::symbol:-_-_-_-_',
  'Equal:key:::symbol:=+=+=+=+',
  'Backspace:func:auto:⟻ Backspace:func:Backspace',
  '',
  'Tab:func:auto::func:Tab',
  'KeyQ:key:::letter:qQQqйЙЙй',
  'KeyW:key:::letter:wWWwцЦЦц',
  'KeyE:key:::letter:eEEeуУУу',
  'KeyR:key:::letter:rRRrкККк',
  'KeyT:key:::letter:tTTtеЕЕе',
  'KeyY:key:::letter:yYYyнННн',
  'KeyU:key:::letter:uUUuгГГг',
  'KeyI:key:::letter:iIIiшШШш',
  'KeyO:key:::letter:oOOoщЩЩщ',
  'KeyP:key:::letter:pPPpзЗЗз',
  'BracketLeft:key:::symbol:[{[{хХХх',
  'BracketRight:key:::symbol:]}]}ъЪЪъ',
  'Backslash:key:::symbol:\\|\\|/\\/\\',
  'Delete:func::Del:func:Delete',
  '',
  'CapsLock:func:auto:Caps Lock:func:CapsLock',
  'KeyA:key:::letter:aAAaфФФф',
  'KeyS:key:::letter:sSSsыЫЫы',
  'KeyD:key:::letter:dDDdвВВв',
  'KeyF:key:::letter:fFFfаААа',
  'KeyG:key:::letter:gGGgпППп',
  'KeyH:key:::letter:hHHhрРРр',
  'KeyJ:key:::letter:jJJjоООо',
  'KeyK:key:::letter:kKKkлЛЛл',
  'KeyL:key:::letter:lLLlдДДд',
  'Semicolon:key:::symbol:;:;:жЖЖж',
  'Quote:key:::symbol:\'"\'"эЭЭэ',
  'Enter:func:180:↵ Enter:func:Enter',
  '',
  'ShiftLeft:func:auto::func:Shift',
  'KeyZ:key:::letter:zZZzяЯЯя',
  'KeyX:key:::letter:xXXxчЧЧч',
  'KeyC:key:::letter:cCCcсССс',
  'KeyV:key:::letter:vVVvмММм',
  'KeyB:key:::letter:bBBbиИИи',
  'KeyN:key:::letter:nNNnтТТт',
  'KeyM:key:::letter:mMMmьЬЬь',
  'Comma:key:::symbol:,<,<бББб',
  'Period:key:::symbol:.>.>юЮЮю',
  'Slash:key:::symbol:/?/?.,.,',
  'ArrowUp:func::⇧:func:ArrowUp',
  'ShiftRight:func:140::func:Shift',
  '',
  'ControlLeft:func:70:Ctrl:func:Control',
  'MetaLeft:func::Win:func:Meta',
  'AltLeft:func:::func:Alt',
  'Space:space:auto:␣:func:        ',
  'AltRight:func:::func:Alt',
  'ArrowLeft:func::⇦:func:ArrowLeft',
  'ArrowDown:func::⇩:func:ArrowDown',
  'ArrowRight:func::⇨:func:ArrowRight',
  'ControlRight:func:70:Ctrl:func:Control',
];

export default keymap;
