// Format tip: key code : key type : key size :  key title : char type : layout symbols
export const keymap = [
  '',
  'Escape:func:50::func:Esc',
  'Backquote:char:::symbol:`~`~ёЁЁё',
  'Digit1:char:::symbol:1!1!1!1!',
  'Digit2:char:::symbol:2@2@2"2"',
  'Digit3:char:::symbol:3#3#3№3№',
  'Digit4:char:::symbol:4$4$4;4;',
  'Digit5:char:::symbol:5%5%5%5%',
  'Digit6:char:::symbol:6^6^6:6:',
  'Digit7:char:::symbol:7&7&7?7?',
  'Digit8:char:::symbol:8*8*8*8*',
  'Digit9:char:::symbol:9(9(9(9(',
  'Digit0:char:::symbol:0)0)0)0)',
  'Minus:char:::symbol:-_-_-_-_',
  'Equal:char:::symbol:=+=+=+=+',
  'Backspace:func:auto:⟻ Backspace:func:Backspace',
  '',
  'Tab:func:100:Tab:symbol:\t\t\t\t\t\t\t\t',
  'KeyQ:char:::letter:qQQqйЙЙй',
  'KeyW:char:::letter:wWWwцЦЦц',
  'KeyE:char:::letter:eEEeуУУу',
  'KeyR:char:::letter:rRRrкККк',
  'KeyT:char:::letter:tTTtеЕЕе',
  'KeyY:char:::letter:yYYyнННн',
  'KeyU:char:::letter:uUUuгГГг',
  'KeyI:char:::letter:iIIiшШШш',
  'KeyO:char:::letter:oOOoщЩЩщ',
  'KeyP:char:::letter:pPPpзЗЗз',
  'BracketLeft:char:::symbol:[{[{хХХх',
  'BracketRight:char:::symbol:]}]}ъЪЪъ',
  'Backslash:char:::symbol:\\|\\|/\\/\\',
  'Delete:func:auto:Del:func:Delete',
  '',
  'CapsLock:func:auto:Caps Lock:func:CapsLock',
  'KeyA:char:::letter:aAAaфФФф',
  'KeyS:char:::letter:sSSsыЫЫы',
  'KeyD:char:::letter:dDDdвВВв',
  'KeyF:char:::letter:fFFfаААа',
  'KeyG:char:::letter:gGGgпППп',
  'KeyH:char:::letter:hHHhрРРр',
  'KeyJ:char:::letter:jJJjоООо',
  'KeyK:char:::letter:kKKkлЛЛл',
  'KeyL:char:::letter:lLLlдДДд',
  'Semicolon:char:::symbol:;:;:жЖЖж',
  'Quote:char:::symbol:\'"\'"эЭЭэ',
  'Enter:func:175:↵ Enter:symbol:\n\n\n\n\n\n\n\n',
  '',
  'ShiftLeft:func:auto::func:Shift',
  'KeyZ:char:::letter:zZZzяЯЯя',
  'KeyX:char:::letter:xXXxчЧЧч',
  'KeyC:char:::letter:cCCcсССс',
  'KeyV:char:::letter:vVVvмММм',
  'KeyB:char:::letter:bBBbиИИи',
  'KeyN:char:::letter:nNNnтТТт',
  'KeyM:char:::letter:mMMmьЬЬь',
  'Comma:char:::symbol:,<,<бББб',
  'Period:char:::symbol:.>.>юЮЮю',
  'Slash:char:::symbol:/?/?.,.,',
  'ArrowUp:func::⇧:func:ArrowUp',
  'ShiftRight:func:140::func:Shift',
  '',
  'ControlLeft:func:70:Ctrl:func:Control',
  'MetaLeft:func::Win:func:Meta',
  'AltLeft:func:::func:Alt',
  'Space:space:auto:␣:symbol:        ',
  'AltRight:func:::func:Alt',
  'ArrowLeft:func::⇦:func:ArrowLeft',
  'ArrowDown:func::⇩:func:ArrowDown',
  'ArrowRight:func::⇨:func:ArrowRight',
  'ControlRight:func:70:Ctrl:func:Control',
];

export default keymap;
