export const keysConfig = [
  'Backquote:k:::symbol:`~`~ёЁЁё',
  'Digit1:k:::symbol:1!1!1!1!',
  'Digit2:k:::symbol:2@2@2"2"',
  'Digit3:k:::symbol:3#3#3№3№',
  'Digit4:k:::symbol:4$4$4;4;',
  'Digit5:k:::symbol:5%5%5%5%',
  'Digit6:k:::symbol:6^6^6:6:',
  'Digit7:k:::symbol:7&7&7?7?',
  'Digit8:k:::symbol:8*8*8*8*',
  'Digit9:k:::symbol:9(9(9(9(',
  'Digit0:k:::symbol:0)0)0)0)',
  'Minus:k:::symbol:-_-_-_-_',
  'Equal:k:::symbol:=+=+=+=+',
  'Backspace:f:auto:⟻ Backspace:func:Backspace',
  '',
  'Tab:f:auto::func:Tab',
  'KeyQ:k:::letter:qQQqйЙЙй',
  'KeyW:k:::letter:wWWwцЦЦц',
  'KeyE:k:::letter:eEEeуУУу',
  'KeyR:k:::letter:rRRrкККк',
  'KeyT:k:::letter:tTTtеЕЕе',
  'KeyY:k:::letter:yYYyнННн',
  'KeyU:k:::letter:uUUuгГГг',
  'KeyI:k:::letter:iIIiшШШш',
  'KeyO:k:::letter:oOOoщЩЩщ',
  'KeyP:k:::letter:pPPpзЗЗз',
  'BracketLeft:k:::symbol:[{[{хХХх',
  'BracketRight:k:::symbol:]}]}ъЪЪъ',
  'Backslash:k:::symbol:\\|\\|/\\/\\',
  'Delete:f::Del:func:Delete',
  '',
  'CapsLock:f:auto:Caps Lock:func:CapsLock',
  'KeyA:k:::letter:aAAaфФФф',
  'KeyS:k:::letter:sSSsыЫЫы',
  'KeyD:k:::letter:dDDdвВВв',
  'KeyF:k:::letter:fFFfаААа',
  'KeyG:k:::letter:gGGgпППп',
  'KeyH:k:::letter:hHHhрРРр',
  'KeyJ:k:::letter:jJJjоООо',
  'KeyK:k:::letter:kKKkлЛЛл',
  'KeyL:k:::letter:lLLlдДДд',
  'Semicolon:k:::symbol:;:;:жЖЖж',
  'Quote:k:::symbol:\'"\'"эЭЭэ',
  'Enter:f:180:↵ Enter:func:Enter',
  '',
  'ShiftLeft:f:auto::func:Shift',
  'KeyZ:k:::letter:zZZzяЯЯя',
  'KeyX:k:::letter:xXXxчЧЧч',
  'KeyC:k:::letter:cCCcсССс',
  'KeyV:k:::letter:vVVvмММм',
  'KeyB:k:::letter:bBBbиИИи',
  'KeyN:k:::letter:nNNnтТТт',
  'KeyM:k:::letter:mMMmьЬЬь',
  'Comma:k:::symbol:,<,<бББб',
  'Period:k:::symbol:.>.>юЮЮю',
  'Slash:k:::symbol:/?/?.,.,',
  'ArrowUp:f::⇧:func:ArrowUp',
  'ShiftRight:f:140::func:Shift',
  '',
  'ControlLeft:f:70:Ctrl:func:Control',
  'MetaLeft:f::Win:func:Meta',
  'AltLeft:f:::func:Alt',
  'Space:s:auto:␣:func:        ',
  'AltRight:f:::func:Alt',
  'ArrowLeft:f::⇦:func:ArrowLeft',
  'ArrowDown:f::⇩:func:ArrowDown',
  'ArrowRight:f::⇨:func:ArrowRight',
  'ControlRight:f:70:Ctrl:func:Control',
];

export default keysConfig;
